### ISSUE TITLE
Source Data for OpenSans

### ISSUE THREAD

**Issue by pichotta** [TypeNetwork/OpenSans#1]
@m4rc1e @michelleperham 

Hi Marc,

What do you recommend for the best source data for OpenSans?  Would you like us to use the TTFs currently being served on fonts.google.com?   or is there some cubic data around?

Thanks!

Jill

**Comment by m4rc1e** [comment]
Hello,

@laerm0 was the last person to work on this project. I recommend using his repo https://github.com/laerm0/opensans as a starting point.

**Comment by pichotta** [comment]
Would @larem0 be able to accept the open pull request?

https://github.com/laerm0/opensans/pull/28

**Comment by laerm0** [comment]
Sorry about that, you're all set now.
